### ISSUE TITLE
跨平台兼容性问题

### ISSUE THREAD

**Issue by frg2089** [Cylearun-starforge/UniRA2Client#1]
这第一个Issue我就拿下了！

我注意到这个项目里使用了WPF，
这样做的后果是它只能在Windows平台上使用，
而不能在如GNU/Linux、Mac OS上使用。

如果想要用C#编写功能的话，
可以用Tauri + RPC来实现调用C#代码。

当然，如果这个客户端不对GNU和MacOS提供支持的话可以直接关闭这个Issue。

**Comment by Woodykaixa** [comment]
这issue咋没给我邮件提醒呢。。

设计的时候考虑的是只在windows上面运行。现在的问题我觉得是webview2不支持win7了

**Comment by frg2089** [comment]
没事 再过几年Windows 10都不支持了（

**Comment by Woodykaixa** [comment]
我打算趁着虚幻招人公测，在客户端上报点数据统计一下win7的比例。再考虑要不要支持win7

**Comment by frg2089** [comment]
还有个问题 这个项目好像没有许可证

**Comment by Woodykaixa** [comment]
是的。因为我忘记设置不可见了。现在其实并不算是开源状态

**Comment by frg2089** [comment]
啊这...那我赶紧fork（不是
